### ISSUE TITLE
Use of from_utf8_unchecked is unsound.

### ISSUE THREAD

**Issue by CodesInChaos** [pineapplehunter/rust-base64#1]
You can't guarantee that the input will decode to valid UTF-8 since `decode_string` is a public function not marked unsafe. But strings MUST be valid UTF-8 in Rust.

Use `from_utf8` instead and either return a `Result` from`decode_string` or at the very least unwrap/panic instead of provoking undefined behaviour.

**Comment by pineapplehunter** [comment]
Thanks for the advice. I changed the return type to a Result. I was using the unsafe block because that seemed simple at the time and forgot to replace it. I think it is better now.
